# Generated by Django 4.2.21 on 2025-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_fathers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fathers_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
