# Generated by Django 4.2.21 on 2025-05-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_fathers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fathers_name',
        ),
    ]
