# Generated by Django 4.2.21 on 2025-05-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_fathers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
