# Generated by Django 4.2.21 on 2025-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
